### ISSUE TITLE
How do i join the server?

### ISSUE THREAD

**Issue by Samdan9** [schoolgaminghd/heroku-eaglercraft-server#1]
how do i join the server i made?

**Comment by ghost** [comment]
See, you can't, because this thing is a piece of shit made by an asshole who obviously has no clue what they are doing. It doesn't work for two reasons: BungeeCord doesn't bind to the randomly generated http port, so the application gets killed after like one minute, and also, the bukkit server is run synchronously, so it doesn't matter if BungeeCord binds to the correct port or not, because it never starts.

**Comment by schoolgaminghd** [comment]
> See, you can't, because this thing is a piece of shit made by an asshole who obviously has no clue what they are doing. It doesn't work for two reasons: BungeeCord doesn't bind to the randomly generated http port, so the application gets killed after like one minute, and also, the bukkit server is run synchronously, so it doesn't matter if BungeeCord binds to the correct port or not, because it never starts.

yea, i gave up after i couldn't find out how to make the run.sh file run automatically.

**Comment by Samdan9** [comment]
i forgot to close this
